%YAML:1.0
---
written: 1
min_disp: 16
num_disp: 128
block_size: 3
cn: 3
p1_smoothness: 216
p2_smoothness: 864
disp_12_max: 1
unique_ratio: 5
speckle_win_size: 0
specke_range: 1
filter_gap: 2
sigma: 1
lambda: 1
